### ISSUE TITLE
NoteblockStudio on Mac

### ISSUE THREAD

**Issue by EendEntertainment** [OpenNBS/NoteBlockStudio#407]
**Describe the bug**
I can only export the file as a .NBS but not as an audiotrack or schematic

**To Reproduce**
I don't know if it is reproducible

**Expected behavior**
Support for exporting

**Screenshots**
<img width="2560" alt="image" src="https://github.com/OpenNBS/OpenNoteBlockStudio/assets/128893904/9a2e8837-6840-4e50-b703-261fc3199259">

**Additional context**
macOS Monterey
3,3 GHz 6-Core Intel Core i5
8 GB 2667 MHz DDR4
AMD Radeon Pro 5300 4 GB

**(PS)**
I can't update to the 3.10.0 version of NoteblockStudio

**Comment by chenxi050402** [comment]
Hello!
Currently, onbs builds for other platforms are unofficial and not supported. The cross platform branch currently misses libraries for exporting, so they were disabled for other platforms. You will need to use a windows virtual machine or crossover to use the export features on macOS.
