### ISSUE TITLE
Flat symbol setting inconsistent

### ISSUE THREAD

**Issue by ToonLWind** [OpenNBS/NoteBlockStudio#412]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the enhancement you'd like**
I have been using the setting "Use flat symbol" with a project of mine, and I recently turned on the setting "Show note chart when hovering over keys" and I noticed that the note chart still displays the sharp symbol. It would be nice if the note chart displayed the flat symbol when the setting is chosen.

**Additional context**
A screenshot of the problem
![image](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/81862508/34108986-a528-4b10-ad76-1ad8e2cd3257)

**Comment by Bentroen** [comment]
Fixed in d8e09b814dfd5e83cf91ffc7419a8c6981141bbc
