### ISSUE TITLE
Note blocks not importing through nbt structure block in 1.20.1

### ISSUE THREAD

**Issue by GXboy12345** [OpenNBS/NoteBlockStudio#417]
**Describe the bug**
Note blocks do not load, wiring does.

**To Reproduce**
Export any midi as Track Export

**Expected behavior**
Note blocks load

**Screenshots**
![image](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/102619196/a3569ce5-fdd7-4a4d-8095-19ea7b024707)

**Comment by Bentroen** [comment]
Fixed in 716d8230c64d54b91cf937f6e85b19e27fd773a3
