### ISSUE TITLE
Issue with compressing a selection of blocks

### ISSUE THREAD

**Issue by jukmifgguggh1337** [OpenNBS/NoteBlockStudio#44]
Program version 3.4.0
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_menu:

Push :: Execution Error - Variable Index [0,14] out of range [4144,14] - -1.selection_exists(100089,14)
at gml_Script_selection_code_update
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_selection_code_update (line -1)
gml_Script_selection_compress
gml_Script_menu_click
gml_Script_menu_draw
gml_Object_obj_menu_Draw_0

this project has over 10000 blocks so that might be what's causing it

**Comment by ShinkoNet** [comment]
Every second tick needs to be empty for compression to work, it's been this way forever in note block studio. If you expand a selection, add notes inbetween, then compress, you can replicate this error.

**Comment by HielkeMinecraft** [comment]
Just because it's on old issue, doesn't mean we don't want to fix it ;)
Reopening this.

**Comment by Zemogiter** [comment]
I'm having a similiar crash error, version 3.10.0, also trying to compress a song so I can play it at 10 ticks per second 
```
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_menu:

index out of bounds request 26 maximum size is 26############################################################################################
gml_Script_selection_code_update (line 13)
gml_Script_selection_compress (line 89)
gml_Script_menu_click (line 145)
gml_Script_menu_draw (line 188)
gml_Object_obj_menu_Draw_0 (line 0)
```
Is there a way to open ONBS in a debug mode with a command promt window that shows me the full log?
[BW - Vs. Kyurem.nbs.zip](https://github.com/OpenNBS/OpenNoteBlockStudio/files/12762685/BW.-.Vs.Kyurem.nbs.zip)
