### ISSUE TITLE
Code error even on fresh install ("Empty JPEG image")

### ISSUE THREAD

**Issue by Benygreen** [OpenNBS/NoteBlockStudio#459]
**Describe the bug**
When you launch note block studio you get a code error with something about JPEG

**To Reproduce**
1. Open note block studio

**Expected behavior**
Note block studio opens normally

**Comment by Bentroen** [comment]
Hi! Can you please post a screenshot of the error?

**Comment by Benygreen** [comment]
> Hi! Can you please post a screenshot of the error?

![Screenshot (45)](https://github.com/user-attachments/assets/71b58879-c1ee-4679-aa4a-1e1135e56e8e)

**Comment by Bentroen** [comment]
Partially fixed in 8bcb5b5ee79c71f916e957c3a0623569f97ea70f
