### ISSUE TITLE
Volume slider number marker goes past intended range

### ISSUE THREAD

**Issue by BedrRedstone** [OpenNBS/NoteBlockStudio#462]
Dragging the volume button past the sliding range cause the number marker to go past it

1. Go to player mode
2. Drag the volume slider past the bar
3. The marker will appear past or before the slider

I think the number marker should stay in the range

heres some screenshots to understand what im saying
![image](https://github.com/user-attachments/assets/142ee173-2dfc-4803-b422-72abe06355d5)
![Screenshot 2024-07-25 195143](https://github.com/user-attachments/assets/c6f24e30-dc59-498b-a8e2-4725d1f01f0f)

**Comment by Bentroen** [comment]
Confirmed! Thanks for reporting.
