### ISSUE TITLE
Adding new layer above solo layers causes the buttons to break

### ISSUE THREAD

**Issue by BedrRedstone** [OpenNBS/NoteBlockStudio#463]
Adding a new layer above a solo layer moves the toggled buttons to the layer below and deactivates the button toggle on the old one

1. Make a new song
2. Click on "Solo this layer"
4. Add a new layer above the soloed layer
5. Toggle breaks

**Expected behavior**
The layers that were soloed should keep the same toggle, even when a new layer is added

![image](https://github.com/user-attachments/assets/82eb4852-6741-4851-a3e7-e5842bf8dc38)

**Comment by Bentroen** [comment]
Thanks for reporting the issue! I believe this should be an easy fix - will have a look at it for 3.11.

Also, I updated your reproduction steps a little to clarify that you should lock two layers in order for it to work.

**Comment by BedrRedstone** [comment]
> Thanks for reporting the issue! I believe this should be an easy fix - will have a look at it for 3.11.
> 
> Also, I updated your reproduction steps a little to clarify that you should lock two layers in order for it to work.

Actually, this doesnt need two locked layers
![image](https://github.com/user-attachments/assets/7399728e-f8c8-4000-adcf-9489f9d185bf)

**Comment by Bentroen** [comment]
> > Thanks for reporting the issue! I believe this should be an easy fix - will have a look at it for 3.11.
> > 
> > Also, I updated your reproduction steps a little to clarify that you should lock two layers in order for it to work.
> 
> Actually, this doesnt need two locked layers
> ![image](https://github.com/user-attachments/assets/7399728e-f8c8-4000-adcf-9489f9d185bf)
> 

Ah, my bad! The screenshot made me think otherwise. 😅
