### ISSUE TITLE
FPS affects flashing speed when remapping piano keyboard shortcuts

### ISSUE THREAD

**Issue by Bentroen** [OpenNBS/NoteBlockStudio#467]
When right-clicking a piano key to rebind its keyboard shortcut, the currently bound key will flash to indicate it's about to be remapped. However, the flashing rate changes according to the user's FPS setting.

Setting it to 60 FPS makes it flash at twice the intended rate, while 240 FPS makes it flash eight times faster.

**Comment by BedrRedstone** [comment]
looks like someone forgot to use delta time (or whatever its equivelent)
