### ISSUE TITLE
Ctrl+T Causes application to softlock

### ISSUE THREAD

**Issue by BedrRedstone** [OpenNBS/NoteBlockStudio#470]
Using Ctrl+T in any of the three edit modes without selecting any notes causes the application to softlock

1. Open any song
2. Select notes and apply any macro
3. Select either Velocity, Panning, or Pitch
4. Press Ctrl+T

Pressing Ctrl+T without selecting any notes should result in nothing happening

![image](https://github.com/user-attachments/assets/86587e5e-68a9-4088-999e-6fe3719dff3d)

**Comment by CreeperPookie** [comment]
I was also able to trigger this by just making a new file, switching to one of the modes, and pressing CTRL + T; I think this could also be related to how autosave and macros didn't completely close the open GUI (#442, #107)
there is a temporary workaround though: pressing F3 + C force closes the open window, and this does get you back into the normal view; it won't prevent it from triggering though!
