### ISSUE TITLE
Selecting a layer which is already selected should deselect it

### ISSUE THREAD

**Issue by Bentroen** [OpenNBS/NoteBlockStudio#476]
By @overlordvizeon on Discord:

> Suggestion: If the layer you wish to select is already selected, it should deselect it

Considerations:

- Right now the program doesn't keep track of which layers have been selected, as selections operate purely at note block level. As such, we can't detect if a layer is entirely selected without checking all notes in the layer.
- One way around it would be checking only the first (leftmost) note block in the layer and using it to determine if the layer is selected. This would 'work' for most purposes but would lead to a bit of inconsistent behavior.
- Alternatively, shift-clicking the 'Select all blocks in this layer' button could be used as a shortcut to deselect the layer, regardless of its current selection status. Though this is a bit more cumbersome in terms of UX than a simple toggle.

Relates to: #464

**Comment by chenxi050402** [comment]
I think right clicking the select layer button to deselect would be a good way to go, since it's also the way to deselect individual notes
