### ISSUE TITLE
Make fade out multiply the velocity of a block by the fade instead of it just setting the values.

### ISSUE THREAD

**Issue by BedrRedstone** [OpenNBS/NoteBlockStudio#484]
I always hate that the fade out macro never takes into account the current velocity of the notes that are being faded.

I want the notes to instead of being a set value when the macro is used, to be a percentage of the value that is being used.

**Comment by Bentroen** [comment]
Fixed in beacf6a0b61e97073bfc7abac4220e33b575138c
