### ISSUE TITLE
The More instruments... button uses wrong arrow icons

### ISSUE THREAD

**Issue by IoeCmcomc** [OpenNBS/NoteBlockStudio#485]
**Describe the bug**
The "More instruments..." button shows the upward arrow icon when instruments are not expanded and the downward arrow icon when they are expanded.

**To reproduce**
1. Open any song
2. Reduce the window width until the "More instruments..." button appears.
4. See the wrong icon

**Expected behavior**
The button should display the downward icon when instruments are not expanded and vice versa.

**Screenshots**
![image](https://github.com/user-attachments/assets/c23084a1-ee03-4039-8d80-93e6d432ab82)
![image](https://github.com/user-attachments/assets/07bdfae2-1174-4ef7-acf4-6e02d6bd8d1e)

**Additional context**
This should be easy to fix. Unfortunately, I don't have time to fix this myself.

**Comment by chenxi050402** [comment]
This is the intended behavior. Though it would be more intuitive to use a right arrow for its collapsed state.

**Comment by Bentroen** [comment]
Confirmed. Only happens with high-resolution textures enabled - the arrows are swapped compared to regular textures.
