### ISSUE TITLE
Datapack doesn't work on 1.21.3

### ISSUE THREAD

**Issue by notAsquare1** [OpenNBS/NoteBlockStudio#489]
Description:
When I put the datapack into the datapacks folder, it loads, but the functions don't work. If I change the folder names from `functions` to `function` then the pack doesn't load at all.

1. Make a song
2. Download datapack
3. Extract the zip folder
4. Rename all `functions` folders to `function`
5. Compress it back to zip
6. Place the zip in server/world/datapacks
7. Start server
8. Run `/datapack list` and see that it's not there, and do `/function songname:play` and watch it say unknown function

Expected behavior:
It's supposed to register the datapack in the datapack list and play the song when I run the function

Screenshot:
![image](https://github.com/user-attachments/assets/1b0fff2e-137c-4a86-8030-e6b3e7a6cd9d)

Additional context
If I don't change the folder names then the datapack shows up in the datapack list but doesn't work
When I start the server, it says missing metadata for pack

**Comment by notAsquare1** [comment]
I also tried changing the pack format in pack.mcmeta but that didn't work either

**Comment by chenxi050402** [comment]
https://www.reddit.com/r/MinecraftCommands/comments/1dktsnz/updating_data_packs_from_120_to_121/

you will also need to rename some other folders as well
there is no nbs datapack support for 1.21 yet

**Comment by notAsquare1** [comment]
Oops, I realized that rezipping the folder created a subfolder and minecraft couldn't find pack.mcmeta because it wasn't in the folder. I extracted it, moved everything to the main folder, and fixed everything. For people looking at this with the same problem: set pack format to 48 for 1.21-1.21.3 and 61 for 1.21.4
